//
//  PDFReaderCoordinatorTests.swift
//  InSummaryTests
//
//  RED contract (task 2.1) for child PR #2 (`feat/pdf-engine`) inside the
//  Phase 2 chain `pdf-reader-pencilkit-ink-recovery`. Every test method
//  below pins one of the ten behaviours documented in
//  `openspec/changes/pdf-reader-pencilkit-ink-recovery/tasks.md` §2.1
//  and the corresponding scenario block in
//  `openspec/changes/pdf-reader-pencilkit-ink-recovery/specs/pdf-engine/spec.md`.
//
//  The behaviours encoded here, in the exact order they appear in the task
//  description, are:
//
//    1. The coordinator loads the bundled fixture into its `PDFView`.
//    2. Horizontal mode sets `displayMode = .singlePage` +
//       `displayDirection = .horizontal` + `usePageViewController(true)`.
//    3. Vertical mode sets `displayMode = .singlePageContinuous` +
//       `displayDirection = .vertical`.
//    4. Unknown `paginationModeRaw` falls back to horizontal paginated
//       settings.
//    5. `paginationModeRaw` round-trip preserves the value across a
//       coordinator re-init.
//    6. The coordinator persists only `paginationModeRaw` + `updatedAt` to
//       the SwiftData row; every other field stays equal.
//    7. Missing fixture surfaces `PDFReaderError.fixtureMissing(resource:)`.
//    8. Unreadable fixture surfaces `PDFReaderError.fixtureUnreadable`.
//    9. Non-PDF document surfaces `PDFReaderError.unsupportedDocument(reason:)`.
//   10. Document with non-empty `localFileName` surfaces
//       `PDFReaderError.unsupportedDocument(reason:)`.
//   11. (TRIANGULATE — task 2.5) `setPaginationMode` calls
//       `modelContext.save()` and the persisted row's `updatedAt`
//       advances while every other field stays equal. This
//       triangulation is the angle the existing behaviour 6 leaves
//       uncovered: behaviour 6 calls `try context.save()` itself
//       after the setter, so it cannot tell whether the setter
//       invoked `modelContext.save()` on its own. Behaviour 11
//       removes the explicit save, observes the persisted state via
//       a fresh `ModelContext`, and pins `hasChanges == false`
//       after the setter returns.
//
//  RED contract: this file is the failing test for the RED step. The
//  production types `PDFReaderCoordinator` and `PDFReaderError` are
//  intentionally absent in this slice, so every test below must fail at
//  compile time on the unresolved type references before any test method
//  ever executes. The compile failure is the strict-TDD RED signal — it
//  proves the test encodes the contract before the production code is
//  authored. GREEN belongs to task 2.2 (`PDFReaderError`) and task 2.3
//  (`PDFReaderCoordinator`); the RED snapshot stays byte-identical until
//  those tasks land.
//

import XCTest
import SwiftData
import PDFKit
import Foundation
@testable import InSummary

@MainActor
final class PDFReaderCoordinatorTests: XCTestCase {

    // MARK: - Behaviour 1: bundle load

    /// The coordinator opens the bundled `sample-bundle.pdf` and exposes
    /// the parsed `PDFDocument` through its `pdfView.document` property.
    /// Page count is asserted against the canonical 20-page fixture
    /// generated by `PDFFixtureGenerator` and bundled in PR #1.
    func test_coordinatorLoadsBundledFixtureIntoPDFView() throws {
        let document = makeSeedDocument()
        let container = makeSchemaContainer()
        let context = ModelContext(container)
        context.insert(document)
        try context.save()

        let coordinator = try PDFReaderCoordinator(document: document, modelContext: context)

        let pdfDocument = try XCTUnwrap(
            coordinator.pdfView.document,
            "PDFReaderCoordinator.pdfView.document must be non-nil after init against the bundled fixture"
        )
        XCTAssertEqual(
            pdfDocument.pageCount,
            20,
            "The bundled sample-bundle.pdf must parse to a 20-page PDFDocument; got \(pdfDocument.pageCount)"
        )
    }

    // MARK: - Behaviour 2: horizontal paginated mode

    /// Horizontal paginated mode maps to
    /// `displayMode = .singlePage` + `displayDirection = .horizontal` +
    /// `usePageViewController(true)`. The horizontal swipe gesture is
    /// PDFKit's default behaviour under this configuration.
    func test_horizontalModeSetsSinglePageHorizontalPDFView() throws {
        let document = makeSeedDocument()
        document.paginationModeRaw = "horizontal"
        let context = ModelContext(makeSchemaContainer())
        context.insert(document)
        try context.save()

        let coordinator = try PDFReaderCoordinator(document: document, modelContext: context)

        XCTAssertEqual(
            coordinator.pdfView.displayMode,
            .singlePage,
            "Horizontal pagination must set PDFDisplayMode.singlePage; got \(coordinator.pdfView.displayMode)"
        )
        XCTAssertEqual(
            coordinator.pdfView.displayDirection,
            .horizontal,
            "Horizontal pagination must set PDFDisplayDirection.horizontal; got \(coordinator.pdfView.displayDirection)"
        )
        XCTAssertTrue(
            coordinator.pdfView.usePageViewController,
            "Horizontal pagination must set usePageViewController(true); got \(coordinator.pdfView.usePageViewController)"
        )
    }

    // MARK: - Behaviour 3: vertical continuous mode

    /// Vertical continuous mode maps to
    /// `displayMode = .singlePageContinuous` +
    /// `displayDirection = .vertical`. The document scrolls continuously
    /// through pages under this configuration.
    func test_verticalModeSetsSinglePageContinuousVerticalPDFView() throws {
        let document = makeSeedDocument()
        document.paginationModeRaw = "vertical"
        let context = ModelContext(makeSchemaContainer())
        context.insert(document)
        try context.save()

        let coordinator = try PDFReaderCoordinator(document: document, modelContext: context)

        XCTAssertEqual(
            coordinator.pdfView.displayMode,
            .singlePageContinuous,
            "Vertical pagination must set PDFDisplayMode.singlePageContinuous; got \(coordinator.pdfView.displayMode)"
        )
        XCTAssertEqual(
            coordinator.pdfView.displayDirection,
            .vertical,
            "Vertical pagination must set PDFDisplayDirection.vertical; got \(coordinator.pdfView.displayDirection)"
        )
    }

    // MARK: - Behaviour 4: unknown pagination fallback

    /// A `paginationModeRaw` value other than `"horizontal"` or `"vertical"`
    /// falls back to horizontal paginated mode. The spec requires the
    /// coordinator to log the unknown value once via `os.Logger`; that
    /// side-effect is out of scope for this RED contract but the fallback
    /// is asserted here.
    func test_unknownPaginationModeRawFallsBackToHorizontal() throws {
        let document = makeSeedDocument()
        document.paginationModeRaw = "garbage-value"
        let context = ModelContext(makeSchemaContainer())
        context.insert(document)
        try context.save()

        let coordinator = try PDFReaderCoordinator(document: document, modelContext: context)

        XCTAssertEqual(
            coordinator.pdfView.displayMode,
            .singlePage,
            "Unknown paginationModeRaw must fall back to PDFDisplayMode.singlePage; got \(coordinator.pdfView.displayMode)"
        )
        XCTAssertEqual(
            coordinator.pdfView.displayDirection,
            .horizontal,
            "Unknown paginationModeRaw must fall back to PDFDisplayDirection.horizontal; got \(coordinator.pdfView.displayDirection)"
        )
        XCTAssertTrue(
            coordinator.pdfView.usePageViewController,
            "Unknown paginationModeRaw must fall back to usePageViewController(true); got \(coordinator.pdfView.usePageViewController)"
        )
    }

    // MARK: - Behaviour 5: round-trip across coordinator re-init

    /// After the user toggles the pagination preference and the
    /// coordinator is discarded, a fresh coordinator opened against the
    /// same persisted document must honour the persisted value. This is
    /// the preference-round-trip contract from
    /// `openspec/changes/pdf-reader-pencilkit-ink-recovery/specs/pdf-engine/spec.md`
    /// "Round-trip across coordinator re-init".
    func test_paginationModeRoundTripsAcrossCoordinatorReInit() throws {
        let document = makeSeedDocument()
        document.paginationModeRaw = "horizontal"
        let container = makeSchemaContainer()
        let context = ModelContext(container)
        context.insert(document)
        try context.save()

        do {
            let coordinator = try PDFReaderCoordinator(document: document, modelContext: context)
            coordinator.paginationMode = .vertical
        }

        let reloaded = try XCTUnwrap(
            try container.mainContext.fetch(FetchDescriptor<DocumentItem>()).first,
            "The seed DocumentItem must survive a save / fetch round-trip"
        )
        XCTAssertEqual(
            reloaded.paginationModeRaw,
            "vertical",
            "Toggling the coordinator must persist paginationModeRaw = \"vertical\"; got \"\(reloaded.paginationModeRaw)\""
        )

        let rehydratedContext = ModelContext(container)
        let coordinator = try PDFReaderCoordinator(document: reloaded, modelContext: rehydratedContext)
        XCTAssertEqual(
            coordinator.pdfView.displayMode,
            .singlePageContinuous,
            "Re-initialised coordinator must apply vertical PDFDisplayMode; got \(coordinator.pdfView.displayMode)"
        )
        XCTAssertEqual(
            coordinator.pdfView.displayDirection,
            .vertical,
            "Re-initialised coordinator must apply vertical PDFDisplayDirection; got \(coordinator.pdfView.displayDirection)"
        )
    }

    // MARK: - Behaviour 6: only paginationModeRaw + updatedAt persist

    /// Toggling the pagination preference must persist only
    /// `paginationModeRaw` and `updatedAt` to the SwiftData row. Every
    /// other `DocumentItem` field must remain byte-equal across the
    /// toggle. This pins the Phase 1 invariant: the coordinator does not
    /// add, alter, default, or migrate any Phase 1 entity field.
    func test_onlyPaginationModeRawAndUpdatedAtPersistAcrossToggle() throws {
        let originalCreatedAt = Date(timeIntervalSince1970: 1_700_000_000)
        let originalUpdatedAt = Date(timeIntervalSince1970: 1_700_000_000)
        let originalLocator = Data([0x01, 0x02, 0x03])

        let document = DocumentItem()
        document.title = "Getting Started"
        document.fileTypeRaw = "pdf"
        document.fileExtension = "pdf"
        document.localFileName = ""
        document.fileSize = 12_345
        document.contentHash = "deadbeefcafebabe"
        document.lastReadLocator = originalLocator
        document.lastReadPageIndex = 4
        document.totalPages = 20
        document.paginationModeRaw = "horizontal"
        document.createdAt = originalCreatedAt
        document.updatedAt = originalUpdatedAt

        let container = makeSchemaContainer()
        let context = ModelContext(container)
        context.insert(document)
        try context.save()

        let coordinator = try PDFReaderCoordinator(document: document, modelContext: context)
        coordinator.paginationMode = .vertical
        try context.save()

        let reloaded = try XCTUnwrap(
            try container.mainContext.fetch(FetchDescriptor<DocumentItem>()).first,
            "The DocumentItem must round-trip through the container"
        )

        // Unchanged fields — must be byte-equal to the original values.
        XCTAssertEqual(reloaded.title, "Getting Started")
        XCTAssertEqual(reloaded.fileTypeRaw, "pdf")
        XCTAssertEqual(reloaded.fileExtension, "pdf")
        XCTAssertEqual(reloaded.localFileName, "")
        XCTAssertEqual(reloaded.fileSize, 12_345)
        XCTAssertEqual(reloaded.contentHash, "deadbeefcafebabe")
        XCTAssertEqual(reloaded.lastReadLocator, originalLocator)
        XCTAssertEqual(reloaded.lastReadPageIndex, 4)
        XCTAssertEqual(reloaded.totalPages, 20)
        XCTAssertEqual(reloaded.createdAt, originalCreatedAt)

        // Mutated fields — only `paginationModeRaw` + `updatedAt` may change.
        XCTAssertEqual(
            reloaded.paginationModeRaw,
            "vertical",
            "Toggling the coordinator must persist paginationModeRaw = \"vertical\""
        )
        XCTAssertGreaterThan(
            reloaded.updatedAt,
            originalUpdatedAt,
            "Toggling the coordinator must advance DocumentItem.updatedAt past the original value"
        )
    }

    // MARK: - Behaviour 7: missing fixture surfaces fixtureMissing(resource:)

    /// When the bundle does not contain the requested resource, the
    /// coordinator throws `PDFReaderError.fixtureMissing(resource:)`. The
    /// thrown error must carry the same resource name the caller passed
    /// in so the recoverable-error banner can point the user at the
    /// missing asset by name.
    func test_missingFixtureSurfacesFixtureMissingError() throws {
        let document = makeSeedDocument()
        let context = ModelContext(makeSchemaContainer())
        context.insert(document)
        try context.save()

        let isolatedBundle = try makeIsolatedBundle()

        XCTAssertThrowsError(
            try PDFReaderCoordinator(
                document: document,
                modelContext: context,
                bundle: isolatedBundle,
                resourceName: "non-existent-resource",
                resourceExtension: "pdf"
            ),
            "PDFReaderCoordinator must throw when the bundle has no resource matching the requested name"
        ) { error in
            guard case PDFReaderError.fixtureMissing(let resource) = error else {
                XCTFail("Expected PDFReaderError.fixtureMissing(resource:), got \(error)")
                return
            }
            XCTAssertEqual(
                resource,
                "non-existent-resource",
                "fixtureMissing must carry the requested resource name; got \"\(resource)\""
            )
        }
    }

    // MARK: - Behaviour 8: unreadable fixture surfaces fixtureUnreadable

    /// When the bundle contains the requested resource but its bytes do
    /// not parse into a `PDFDocument`, the coordinator throws
    /// `PDFReaderError.fixtureUnreadable`. The reader surface must show a
    /// recoverable error rather than presenting an empty `PDFView`.
    func test_unreadableFixtureSurfacesFixtureUnreadableError() throws {
        let document = makeSeedDocument()
        let context = ModelContext(makeSchemaContainer())
        context.insert(document)
        try context.save()

        let junkBundle = try makeBundleContainingJunkPDF(resourceName: "junk")

        XCTAssertThrowsError(
            try PDFReaderCoordinator(
                document: document,
                modelContext: context,
                bundle: junkBundle,
                resourceName: "junk",
                resourceExtension: "pdf"
            ),
            "PDFReaderCoordinator must throw when the bundled fixture bytes are not a valid PDFDocument"
        ) { error in
            guard case PDFReaderError.fixtureUnreadable = error else {
                XCTFail("Expected PDFReaderError.fixtureUnreadable, got \(error)")
                return
            }
        }
    }

    // MARK: - Behaviour 9: non-PDF document surfaces unsupportedDocument(reason:)

    /// Documents whose `fileTypeRaw` is not `"pdf"` are refused at the
    /// coordinator boundary. The reader surface must show a recoverable
    /// "not supported in this build" error rather than opening a wrong
    /// document type.
    func test_nonPDFDocumentSurfacesUnsupportedDocumentError() throws {
        let document = makeSeedDocument()
        document.fileTypeRaw = "epub"
        let context = ModelContext(makeSchemaContainer())
        context.insert(document)
        try context.save()

        XCTAssertThrowsError(
            try PDFReaderCoordinator(document: document, modelContext: context),
            "PDFReaderCoordinator must throw when DocumentItem.fileTypeRaw is not \"pdf\""
        ) { error in
            guard case PDFReaderError.unsupportedDocument(let reason) = error else {
                XCTFail("Expected PDFReaderError.unsupportedDocument(reason:), got \(error)")
                return
            }
            XCTAssertFalse(
                reason.isEmpty,
                "unsupportedDocument must carry a non-empty reason so the recoverable-error banner can describe the refusal"
            )
        }
    }

    // MARK: - Behaviour 10: document with non-empty localFileName surfaces unsupportedDocument(reason:)

    /// Documents whose `localFileName` is non-empty are also refused at
    /// the coordinator boundary. Phase 2 is reachable only from the
    /// bundled seed PDF (`localFileName.isEmpty == true`); any
    /// user-imported row is out of scope until the Phase 5 import work.
    func test_documentWithNonEmptyLocalFileNameSurfacesUnsupportedDocumentError() throws {
        let document = makeSeedDocument()
        document.localFileName = "abc-123.pdf"
        let context = ModelContext(makeSchemaContainer())
        context.insert(document)
        try context.save()

        XCTAssertThrowsError(
            try PDFReaderCoordinator(document: document, modelContext: context),
            "PDFReaderCoordinator must throw when DocumentItem.localFileName is non-empty"
        ) { error in
            guard case PDFReaderError.unsupportedDocument(let reason) = error else {
                XCTFail("Expected PDFReaderError.unsupportedDocument(reason:), got \(error)")
                return
            }
            XCTAssertFalse(
                reason.isEmpty,
                "unsupportedDocument must carry a non-empty reason so the recoverable-error banner can describe the refusal"
            )
        }
    }

    // MARK: - Behaviour 11: TRIANGULATE — setPaginationMode calls modelContext.save() and advances updatedAt

    /// TRIANGULATE (task 2.5): the `paginationMode` setter must call
    /// `modelContext.save()` so the new pagination preference and the
    /// advanced `updatedAt` are persisted atomically with the toggle,
    /// and the persisted write set must remain
    /// `{paginationModeRaw, updatedAt}` — every other `DocumentItem`
    /// field stays equal.
    ///
    /// This triangulation pins the persistence boundary from three
    /// angles that the existing behaviour 6
    /// (`test_onlyPaginationModeRawAndUpdatedAtPersistAcrossToggle`)
    /// does NOT cover:
    ///
    /// 1. **No explicit `try context.save()` in the test.** Behaviour 6
    ///    calls `try context.save()` *after* the setter, which means
    ///    the test passes even if the setter itself forgets to call
    ///    `save()`. Behaviour 11 deliberately OMITS that explicit
    ///    save, so the only way the mutations reach the backing store
    ///    is via the setter's own `try modelContext.save()` call.
    /// 2. **Fresh `ModelContext` fetch.** A fresh `ModelContext`
    ///    built from the same container has its own in-memory cache;
    ///    uncommitted mutations on `context` are NOT visible from
    ///    `verifyContext`. Observing the new `paginationModeRaw`
    ///    and `updatedAt` from a fresh fetch is a direct signal that
    ///    `save()` was called and the backing store reflects the
    ///    toggle. If the setter forgot the `save()`, this fetch
    ///    would return `paginationModeRaw == "horizontal"` (the
    ///    persisted baseline) and `updatedAt == originalUpdatedAt`.
    /// 3. **`modelContext.hasChanges == false` after the setter.**
    ///    The setter mutates the row then must drain those mutations
    ///    via `modelContext.save()`. If the setter forgot the
    ///    `save()`, `hasChanges` would still be `true`. A pre-toggle
    ///    baseline assertion guarantees the coordinator's `init`
    ///    does not author any uncommitted mutations that would
    ///    confound the post-toggle check.
    /// 4. **Every other field stays byte-equal.** The setter must
    ///    only mutate `{paginationModeRaw, updatedAt}`; every other
    ///    `DocumentItem` field must round-trip through the fresh
    ///    fetch equal to its pre-toggle value. This is the Phase 1
    ///    invariant: the coordinator does not add, alter, default,
    ///    or migrate any Phase 1 entity field.
    func test_setPaginationModeCallsModelContextSaveAndAdvancesUpdatedAtWhileOtherFieldsStayEqual() throws {
        let originalCreatedAt = Date(timeIntervalSince1970: 1_700_000_000)
        let originalUpdatedAt = Date(timeIntervalSince1970: 1_700_000_000)
        let originalLocator = Data([0x01, 0x02, 0x03])

        let document = DocumentItem()
        document.title = "Getting Started"
        document.fileTypeRaw = "pdf"
        document.fileExtension = "pdf"
        document.localFileName = ""
        document.fileSize = 12_345
        document.contentHash = "deadbeefcafebabe"
        document.lastReadLocator = originalLocator
        document.lastReadPageIndex = 4
        document.totalPages = 20
        document.paginationModeRaw = "horizontal"
        document.createdAt = originalCreatedAt
        document.updatedAt = originalUpdatedAt

        let container = makeSchemaContainer()
        let context = ModelContext(container)
        context.insert(document)
        try context.save()

        let coordinator = try PDFReaderCoordinator(document: document, modelContext: context)

        // Pre-toggle baseline: the modelContext must have no pending
        // changes after the coordinator's `init` + the explicit
        // baseline `save()`. If the `init` left any mutations
        // uncommitted, the post-toggle `hasChanges == false`
        // assertion below would falsely pass.
        XCTAssertFalse(
            context.hasChanges,
            "Before the setter: modelContext.hasChanges must be false (no pending mutations after init + baseline save)"
        )

        // The setter MUST call `modelContext.save()` to drain the
        // paginationModeRaw + updatedAt mutations it authors.
        // Unlike behaviour 6, this test does NOT call
        // `try context.save()` afterwards — the only path for the
        // mutations to reach the backing store is the setter's own
        // `try modelContext.save()` call.
        coordinator.paginationMode = .vertical

        // Triangulation angle #1: `modelContext.hasChanges` must be
        // false after the setter. The setter mutated
        // `paginationModeRaw` + `updatedAt`, then called
        // `modelContext.save()` to drain the pending changes. If
        // the setter forgot to call `save()`, `hasChanges` would
        // still be `true`.
        XCTAssertFalse(
            context.hasChanges,
            "After setPaginationMode: modelContext.hasChanges must be false — the setter must have called modelContext.save() to drain the pending paginationModeRaw + updatedAt mutations"
        )

        // Triangulation angle #2: a fresh `ModelContext` fetched
        // from the same container must observe the new persisted
        // state. The fresh context has its own in-memory cache;
        // uncommitted mutations on `context` are NOT visible from
        // `verifyContext`. If the setter did NOT call `save()`,
        // this fetch would return `paginationModeRaw == "horizontal"`
        // (the persisted baseline).
        let verifyContext = ModelContext(container)
        let reloaded = try XCTUnwrap(
            try verifyContext.fetch(FetchDescriptor<DocumentItem>()).first,
            "The DocumentItem must round-trip through the container"
        )

        // Mutated fields — exactly the documented write set.
        XCTAssertEqual(
            reloaded.paginationModeRaw,
            "vertical",
            "setPaginationMode must persist paginationModeRaw == \"vertical\"; a fresh fetch returning \"horizontal\" means the setter did not call modelContext.save()"
        )
        XCTAssertGreaterThan(
            reloaded.updatedAt,
            originalUpdatedAt,
            "setPaginationMode must advance DocumentItem.updatedAt past the original value"
        )

        // Unchanged fields — must be byte-equal to the original
        // values. The setter must NOT alter any field beyond the
        // documented `{paginationModeRaw, updatedAt}` write set.
        XCTAssertEqual(reloaded.title, "Getting Started")
        XCTAssertEqual(reloaded.fileTypeRaw, "pdf")
        XCTAssertEqual(reloaded.fileExtension, "pdf")
        XCTAssertEqual(reloaded.localFileName, "")
        XCTAssertEqual(reloaded.fileSize, 12_345)
        XCTAssertEqual(reloaded.contentHash, "deadbeefcafebabe")
        XCTAssertEqual(reloaded.lastReadLocator, originalLocator)
        XCTAssertEqual(reloaded.lastReadPageIndex, 4)
        XCTAssertEqual(reloaded.totalPages, 20)
        XCTAssertEqual(reloaded.createdAt, originalCreatedAt)
    }

    // MARK: - Helpers

    /// Builds a `DocumentItem` that satisfies the Phase 2 seed contract:
    /// `fileTypeRaw == "pdf"` AND `localFileName.isEmpty == true` AND
    /// `paginationModeRaw == "horizontal"`. Each test that needs a
    /// different starting state mutates the result before insertion.
    private func makeSeedDocument() -> DocumentItem {
        let document = DocumentItem()
        document.title = "Getting Started"
        document.fileTypeRaw = "pdf"
        document.fileExtension = "pdf"
        document.localFileName = ""
        document.paginationModeRaw = "horizontal"
        return document
    }

    /// Creates an empty on-disk directory and returns a `Bundle` rooted at
    /// it. Used by the "missing fixture" test to ensure the bundle
    /// resolution path cannot accidentally hit a resource that lives in
    /// the production app bundle.
    private func makeIsolatedBundle() throws -> Bundle {
        let tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("PDFReaderCoordinatorTests-isolated-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(
            at: tempDir,
            withIntermediateDirectories: true
        )
        guard let bundle = Bundle(url: tempDir) else {
            throw NSError(
                domain: "PDFReaderCoordinatorTests",
                code: 1,
                userInfo: [NSLocalizedDescriptionKey: "Failed to construct isolated Bundle at \(tempDir.path)"]
            )
        }
        return bundle
    }

    /// Writes a file named `<resourceName>.pdf` containing bytes that
    /// are NOT a valid `PDFDocument` into a fresh on-disk directory and
    /// returns a `Bundle` rooted at that directory. Used by the
    /// "unreadable fixture" test to feed the coordinator malformed
    /// bytes that pass the resource-resolution step but fail at parse.
    private func makeBundleContainingJunkPDF(resourceName: String) throws -> Bundle {
        let tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("PDFReaderCoordinatorTests-junk-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(
            at: tempDir,
            withIntermediateDirectories: true
        )
        let junkBytes = Data("this is not a valid PDF document".utf8)
        let junkURL = tempDir.appendingPathComponent("\(resourceName).pdf")
        try junkBytes.write(to: junkURL, options: .atomic)
        guard let bundle = Bundle(url: tempDir) else {
            throw NSError(
                domain: "PDFReaderCoordinatorTests",
                code: 2,
                userInfo: [NSLocalizedDescriptionKey: "Failed to construct junk Bundle at \(tempDir.path)"]
            )
        }
        return bundle
    }
}